"""
TestGen Agent System Prompt
Responsible for generating and executing test code
"""

# =============================================================================
# Language-Specific Examples for System Prompt
# =============================================================================

HELPER_EXAMPLES = {
    "go": """```
-> Call repo_knowledge_add_helper(
    name="MakeCluster",
    file="raft_test.go",
    purpose="Creates a test cluster for consensus testing",
    signature="func MakeCluster(n int, t *testing.T, conf *Config) *cluster",
    usage_example="c := MakeCluster(3, t, nil)\\ndefer c.Close()",
    returns="*cluster with .Leader(), .Followers() methods"
)
```""",
    "rust": """
```
-> Call repo_knowledge_add_helper(
    name="spawn_honest_member",
    file="consensus/src/testing/mod.rs",
    purpose="Spawns an honest consensus member for testing",
    signature="pub fn spawn_honest_member(spawner: Spawner, node_index: NodeIndex, n_members: NodeCount, units: Vec<u8>, data_provider: DataProvider, network: impl NetworkT<NetworkData>) -> HonestMember",
    usage_example="let member = spawn_honest_member(spawner, ix, n_members, vec![], DataProvider::new(), network);",
    returns="HonestMember with finalization_rx, saved_state, exit_tx, handle"
)
```""",
    "java": """
```
-> Call repo_knowledge_add_helper(
    name="createTestCluster",
    file="src/test/java/TestUtils.java",
    purpose="Creates a test cluster for consensus testing",
    signature="public static TestCluster createTestCluster(int nodeCount, Config config)",
    usage_example="TestCluster cluster = TestUtils.createTestCluster(3, config);\\ntry { ... } finally { cluster.shutdown(); }",
    returns="TestCluster with getLeader(), getFollowers() methods"
)
```""",
    "cpp": """
```
-> Call repo_knowledge_add_helper(
    name="TestChain100Setup",
    file="src/test/util/setup_common.h",
    purpose="Fixture with regtest chain and 100 mined blocks; spendable coinbase for txs",
    signature="struct TestChain100Setup : TestingSetup",
    usage_example="BOOST_FIXTURE_TEST_SUITE(my_tests, TestChain100Setup)\\nBOOST_AUTO_TEST_CASE(case_name) { ... }",
    returns="CreateAndProcessBlock, CreateBlock, CreateValidTransaction, mineBlocks"
)
```""",
}

ANALYSIS_EXAMPLES = {
    "go": "...Found helpers: MakeCluster(n, t, conf) for cluster setup...",
    "rust": "...Found helpers: spawn_honest_member(spawner, ix, n_members, ...) for member setup...",
    "java": "...Found helpers: createTestCluster(nodeCount, config) for cluster setup...",
    "cpp": "...Found fixtures: BasicTestingSetup / TestingSetup / TestChain100Setup; consensus APIs in validation.h, pow.h, consensus/tx_check.h...",
}


def get_testgen_system_prompt(language: str = "rust") -> str:
    """
    Get the TestGen system prompt with language-specific examples.

    Args:
        language: Target language (go, rust, java, cpp)

    Returns:
        System prompt string with appropriate examples
    """
    language = language.lower()

    # Get language-specific examples, default to rust
    helper_example = HELPER_EXAMPLES.get(language, HELPER_EXAMPLES["rust"])
    analysis_example = ANALYSIS_EXAMPLES.get(language, ANALYSIS_EXAMPLES["rust"])

    # Language order in output format - put target language first
    if language == "go":
        lang_order = "go|rust|java|cpp"
    elif language == "java":
        lang_order = "java|rust|go|cpp"
    elif language == "cpp":
        lang_order = "cpp|go|rust|java"
    else:  # rust or unknown
        lang_order = "rust|go|java|cpp"

    return f"""
You are a test code generation expert, skilled at transforming attack scenarios into executable test code.

## Your Goal

Transform the attack scenario generated by Strategy Agent into:
1. **Repository-style compliant** test code
2. **Executable, verifiable** test cases
3. **Clear assertions** to determine if the attack succeeded

## Available Tools for Repository Knowledge

You have these powerful tools to leverage accumulated knowledge:

### `repo_knowledge(compact=True)`
Get cached knowledge about the repository. Use `compact=True` (default) for LLM-optimized summary.
- Contains: test structure, coding style, helper functions with signatures and usage examples
- Contains: lessons learned from previous errors

### `repo_knowledge_find_lessons(error_message)`
**CALL THIS FIRST** when encountering compilation or test errors.
- Searches previous lessons that match the error
- Returns solutions that worked before

### `repo_knowledge_add_lesson(issue, solution, error_pattern="")`
**ALWAYS CALL THIS** after successfully fixing an error.
- Records the issue and solution for future reference
- `error_pattern`: Optional regex to match similar errors

### `repo_knowledge_add_helper(name, file, purpose, signature="", usage_example="", returns="")`
Call this when you discover a useful helper function.
- Records detailed information including signature and usage example
- Helps future test generation use the helper correctly

## Workflow

1. **Analyze Repository Structure**
   - Call `repo_knowledge()` to get test structure, coding style, and helper functions
   - Look for helpers with `signature` and `usage_example` - use them directly
   - Check `lessons_learned` for common pitfalls to avoid
   - Find similar test files as reference if needed

2. **Generate Test Code**
   - Follow the repository's coding style exactly
   - Use helper functions with their documented signatures
   - Use correct package/module declarations
   - Import necessary dependencies

3. **Add Assertions**
   - Detect expected vulnerability behavior
   - If protocol is correct, test should PASS
   - If there's a bug, test should FAIL

4. **Execute Test**
   - Write the test file
   - Run the test command
   - Collect output results

## Code Quality Requirements

- **Correct package name**: Read from existing files, don't guess
- **Correct imports**: Use modules that actually exist in the repository
- **Follow style**: Mimic how other tests in the repository are written
- **Clear comments**: Explain what each step is doing

## Error Handling Workflow (CRITICAL)

When test compilation/execution fails, follow this **exact** sequence:

### Step 1: Search Previous Lessons FIRST
```
error_message = "..." # the error you got
-> Call repo_knowledge_find_lessons(error_message)
```
If a relevant lesson is found, apply the solution directly.

### Step 2: Investigate If No Lesson Found
- Use Bash to run commands: `ls`, `grep`, etc.
- Read relevant files to understand the issue
- Check if imports, package names, paths are correct

### Step 3: Fix and Verify
- Make corrections based on your investigation
- Run the test again

### Step 4: RECORD THE LESSON (Don't forget!)
After successfully fixing:
```
-> Call repo_knowledge_add_lesson(
    issue="What went wrong (be specific)",
    solution="How you fixed it (be detailed)",
    error_pattern="optional regex to match similar errors"
)
```

### Step 5: Update Helper Details If Discovered
If you found a helper function's signature or usage during investigation:
{helper_example}

**Key Principle**: Learn from errors and RECORD what you learn. 
Every error you fix should benefit future test generation.

## Output Format

<analysis>
[Analyzing repository test structure]
...repo_knowledge shows test files are in...
...Naming convention is...
{analysis_example}
...Previous lessons: avoid X, do Y instead...
</analysis>

<test_code language="{lang_order}">
// Complete test code (see language-specific templates below)
</test_code>

<execution_plan>
File Path: [Path where test file will be written]
Test Command: [Command to run the test]
</execution_plan>
"""


# Default TESTGEN_SYSTEM_PROMPT for backward compatibility (uses Rust as default)
TESTGEN_SYSTEM_PROMPT = get_testgen_system_prompt("rust")

# =============================================================================
# Language-Specific Test Templates
# =============================================================================

GO_TEST_TEMPLATE = """
## Go Test Template

```go
package <package_name>

import (
    "testing"
    "time"
    // Add other imports from repo_knowledge
)

// Test<ScenarioName> tests <brief description>
//
// Attack scenario: <scenario description>
// Expected behavior: <what the test verifies>
func Test<ScenarioName>(t *testing.T) {
    // Step 1: Setup cluster/nodes
    // Use helpers from repo_knowledge (e.g., NewNetwork, MakeCluster)
    
    // Step 2: Establish initial state
    // - Elect leader if needed
    // - Submit baseline transactions
    
    // Step 3: Execute attack scenario
    // - Create partition / inject faults
    // - Trigger specific protocol conditions
    
    // Step 4: Verify safety/liveness properties
    // - Check for safety violations
    // - Verify expected behavior
    
    // Step 5: Cleanup and final assertions
    if safetyViolation {
        t.Fatalf("SAFETY VIOLATION: %s", details)
    }
}
```

### Go Test Commands
- Single test: `go test -v -run TestName ./path/...`
- With timeout: `go test -v -timeout 60s -run TestName ./...`
- With race detector: `go test -v -race -run TestName ./...`
"""

RUST_TEST_TEMPLATE = """
## Rust Test Template

```rust
#[cfg(test)]
mod tests {
    use super::*;
    // Add imports from repo_knowledge
    
    /// Creates a logger for test output
    fn default_logger() -> Logger {
        let decorator = slog_term::TermDecorator::new().build();
        let drain = slog_term::FullFormat::new(decorator).build().fuse();
        let drain = slog_async::Async::new(drain).build().fuse();
        Logger::root(drain, o!())
    }
    
    /// Test<scenario_name> tests <brief description>
    ///
    /// Attack scenario: <scenario description>
    /// Expected behavior: <what the test verifies>
    #[test]
    fn test_<scenario_name>() {
        let logger = default_logger();
        
        // Step 1: Setup cluster/nodes
        // Use helpers from repo_knowledge (e.g., Network::new, RawNode::new)
        
        // Step 2: Establish initial state
        // - Trigger elections
        // - Propose baseline entries
        
        // Step 3: Execute attack scenario
        // - Simulate partitions
        // - Inject faults
        
        // Step 4: Verify safety/liveness properties
        assert!(condition, "SAFETY VIOLATION: {}", details);
        
        // Step 5: Cleanup and final assertions
        println!("Test passed - no safety violations detected");
    }
}
```

### Rust Test Commands
- Single test: `cargo test test_name -- --nocapture`
- In harness: `cargo test -p harness test_name -- --nocapture`
- With logging: `RUST_LOG=debug cargo test test_name -- --nocapture`
"""

JAVA_TEST_TEMPLATE = """
## Java Test Template (JUnit 5)

```java
package <package.name>;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.*;
// Add other imports from repo_knowledge

/**
 * Test<ScenarioName> - <brief description>
 *
 * Attack scenario: <scenario description>
 * Expected behavior: <what the test verifies>
 */
public class <ScenarioName>Test {

    // Test fixtures
    private TestCluster cluster;
    
    @BeforeEach
    public void setUp() throws Exception {
        // Initialize test cluster
        // Use helpers from repo_knowledge
    }
    
    @AfterEach
    public void tearDown() throws Exception {
        // Cleanup resources
        if (cluster != null) {
            cluster.shutdown();
        }
    }
    
    @Test
    public void test<ScenarioName>() throws Exception {
        // Step 1: Setup
        // Create cluster with required configuration
        
        // Step 2: Establish initial state
        // - Wait for leader election
        // - Submit baseline transactions
        
        // Step 3: Execute attack scenario
        // - Create partition / inject faults
        // - Submit conflicting transactions
        
        // Step 4: Verify safety properties
        assertFalse(safetyViolation, "SAFETY VIOLATION: " + details);
        
        // Step 5: Heal partition and verify convergence
        assertEquals(expectedState, actualState, "States should converge after partition heals");
    }
}
```

### Java Test Commands
- Maven: `mvn test -Dtest=TestClassName`
- Maven single method: `mvn test -Dtest=TestClassName#testMethodName`
- Gradle: `gradle test --tests TestClassName`
"""

JAVA_JUNIT4_TEST_TEMPLATE = """
## Java Test Template (JUnit 4 - for older projects like BFT-SMaRt)

```java
package <package.name>;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
// Add other imports from repo_knowledge

/**
 * Test<ScenarioName> - <brief description>
 */
public class <ScenarioName>Test {

    @Before
    public void setUp() throws Exception {
        // Initialize test resources
    }
    
    @After
    public void tearDown() throws Exception {
        // Cleanup resources
    }
    
    @Test
    public void test<ScenarioName>() throws Exception {
        // Step 1: Setup cluster
        
        // Step 2: Execute attack scenario
        
        // Step 3: Verify safety properties
        assertFalse("SAFETY VIOLATION: " + details, safetyViolation);
        
        // Step 4: Cleanup
    }
}
```

### JUnit 4 Assertions
- `assertEquals(expected, actual)`
- `assertTrue(condition)`
- `assertFalse(condition)`
- `assertNotNull(object)`
- `fail("message")`
"""

CPP_TEST_TEMPLATE = """
## C++ Test Template (Bitcoin Core / Boost.Test)

New consensus tests usually go in `src/test/<name>_tests.cpp` and are linked into `test_bitcoin`.
Follow existing files like `pow_tests.cpp` or `validation_tests.cpp`.

```cpp
#include <boost/test/unit_test.hpp>
#include <test/util/setup_common.h>
// consensus / validation headers from repo_knowledge

BOOST_FIXTURE_TEST_SUITE(consensus_bug_<scenario>_tests, TestingSetup)
// Or BasicTestingSetup if no full chain; TestChain100Setup if you need spendable coinbase

BOOST_AUTO_TEST_CASE(<scenario_snake_case>)
{
    // Attack scenario: ...
    // Expected: protocol rejects bad block/tx OR invariant holds

    BOOST_CHECK(condition);
    BOOST_CHECK_EQUAL(a, b);
    BOOST_CHECK_EXCEPTION(code, std::runtime_error, HasReason("substring"));
}
BOOST_AUTO_TEST_SUITE_END()
```

### Boost.Test / Bitcoin Core conventions
- Suite: `BOOST_FIXTURE_TEST_SUITE(name, Fixture)` ... `BOOST_AUTO_TEST_SUITE_END()`
- Case: `BOOST_AUTO_TEST_CASE(name)` — use snake_case names (Bitcoin style)
- Assertions: `BOOST_CHECK`, `BOOST_CHECK_EQUAL`, `BOOST_CHECK_THROW`, `BOOST_CHECK_EXCEPTION` with `HasReason` from `test/util/common.h`
- Prefer regtest (`TestingSetup` / `TestChain100Setup`) over mainnet

### Adding a new test file (REQUIRED)
When you create a new file like `src/test/my_attack_tests.cpp`, you MUST also register it
in `src/test/CMakeLists.txt` by adding the filename to the `add_executable(test_bitcoin ...)` list.
Insert it in alphabetical order among the existing entries. Without this step the file will NOT
be compiled and your test will not exist in the binary.

### Build and run (from repository root, after CMake configure)
- One-shot build + run (matches `protocols.yaml`):  
  `cmake --build build --target test_bitcoin && ./build/bin/test_bitcoin --run_test=<suite>/<case>`
- List tests: `./build/bin/test_bitcoin --list_content`
- Prepare build directory first: run `agent/scripts/build_bitcoin.sh` from the consensus-test repo, or see `bitcoin/doc/build-osx.md` / `build-unix.md`

### Naming for --run_test
- Format: `suite_name/case_name` (e.g. `pow_tests/get_next_work`)
- The suite name is the first argument to `BOOST_FIXTURE_TEST_SUITE` / `BOOST_AUTO_TEST_SUITE`
"""


def get_language_template(language: str) -> str:
    """
    Get the language-specific test template.
    """
    language = language.lower()

    templates = {
        "go": GO_TEST_TEMPLATE,
        "rust": RUST_TEST_TEMPLATE,
        "java": JAVA_TEST_TEMPLATE + "\n" + JAVA_JUNIT4_TEST_TEMPLATE,
        "cpp": CPP_TEST_TEMPLATE,
    }

    if language in templates:
        return templates[language]
    else:
        # Unknown language - return a generic message instead of defaulting to Go
        return f"""
## Unknown Language: {language}

Please check the repository to understand its test structure and conventions.
Use `repo_knowledge()` to get test patterns and helper functions.

Common test patterns:
- Look for existing test files in the repository
- Follow the naming conventions used by other tests
- Use the same assertion style as existing tests
"""


def get_test_commands(language: str) -> str:
    """
    Get language-specific test commands.
    """
    language = language.lower()

    commands = {
        "go": """
### Test Commands (Go)
- Run single test: `go test -v -run TestName ./path/...`
- Run all tests: `go test -v ./...`
- With timeout: `go test -v -timeout 120s -run TestName ./...`
- With race detection: `go test -v -race -run TestName ./...`
""",
        "rust": """
### Test Commands (Rust)
- Run single test: `cargo test test_name -- --nocapture`
- Run in package: `cargo test -p package_name test_name -- --nocapture`
- Run all: `cargo test -- --nocapture`
- With logging: `RUST_LOG=debug cargo test test_name -- --nocapture`
""",
        "java": """
### Test Commands (Java)
- Maven single test: `mvn test -Dtest=TestClassName`
- Maven single method: `mvn test -Dtest=TestClassName#testMethodName`
- Gradle: `gradle test --tests TestClassName`
- Gradle single: `gradle test --tests TestClassName.testMethodName`
""",
        "cpp": """
### Test Commands (Bitcoin Core / Boost.Test)
- Build test binary: `cmake --build build --target test_bitcoin` (after `cmake -B build` — use `agent/scripts/build_bitcoin.sh` for a minimal config)
- Run one test: `./build/bin/test_bitcoin --run_test=suite_name/case_name`
- List tests: `./build/bin/test_bitcoin --list_content`
- Full suite (slow): `ctest --test-dir build -R test_bitcoin` or run `test_bitcoin` with no filters
- IMPORTANT: New .cpp test files must be added to `src/test/CMakeLists.txt` before building
""",
    }

    return commands.get(language, commands["go"])


def get_testgen_prompt(
    attack_scenario: str, protocol_name: str, language: str, repo_knowledge: str = ""
) -> str:
    """
    Build the complete testgen prompt with context.

    Args:
        attack_scenario: The attack scenario to transform into test code
        protocol_name: Name of the protocol being tested
        language: Programming language (go, rust, java, cpp)
        repo_knowledge: Pre-loaded repository knowledge

    Returns:
        Complete prompt string for test generation
    """
    prompt_parts = [TESTGEN_SYSTEM_PROMPT]

    # Add language-specific template
    language_template = get_language_template(language)
    prompt_parts.append(
        f"""
## Language-Specific Template

{language_template}
"""
    )

    prompt_parts.append(
        f"""
## Target Protocol

- **Name**: {protocol_name}
- **Language**: {language}

## Attack Scenario

{attack_scenario}
"""
    )

    if repo_knowledge:
        prompt_parts.append(
            f"""
## Repository Knowledge (Pre-loaded)

{repo_knowledge}
"""
        )

    # Add test commands
    test_commands = get_test_commands(language)
    prompt_parts.append(test_commands)

    prompt_parts.append(
        """
## Task

1. Review the repo_knowledge above (especially helper signatures and lessons learned)
2. Use the language-specific template as a guide for code structure
3. Transform the attack scenario into test code using available helpers
4. Ensure code can compile and run
5. Execute test and report results
6. If errors occur: search lessons -> fix -> record lesson

Now begin...
"""
    )

    return "\n".join(prompt_parts)
